//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerAddressInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerAddressInfo()
        {
            this.outWarehourse = new HashSet<outWarehourse>();
        }
    
        public string AddressNum { get; set; }
        public string AddressXinxi { get; set; }
        public string customerNum { get; set; }
        public string contacts { get; set; }
        public string phone { get; set; }
        public int isDel { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outWarehourse> outWarehourse { get; set; }
    }
}
