//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CKSJKEntities : DbContext
    {
        public CKSJKEntities()
            : base("name=CKSJKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customerAddressInfo> customerAddressInfo { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LossReport> LossReport { get; set; }
        public virtual DbSet<LossReportDetails> LossReportDetails { get; set; }
        public virtual DbSet<LossReportType> LossReportType { get; set; }
        public virtual DbSet<OutboundType> OutboundType { get; set; }
        public virtual DbSet<outWareDetail> outWareDetail { get; set; }
        public virtual DbSet<outWarehourse> outWarehourse { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productLeix> productLeix { get; set; }
        public virtual DbSet<putWareDetail> putWareDetail { get; set; }
        public virtual DbSet<putWarehourse> putWarehourse { get; set; }
        public virtual DbSet<receiptType> receiptType { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supplierLeix> supplierLeix { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transfer> transfer { get; set; }
        public virtual DbSet<transferDetail> transferDetail { get; set; }
        public virtual DbSet<transferType> transferType { get; set; }
        public virtual DbSet<warehourse> warehourse { get; set; }
    }
}
