//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outWareDetail
    {
        public string OutboundNum { get; set; }
        public string productNum { get; set; }
        public long productCount { get; set; }
        public double totalMoney { get; set; }
        public string LocationNum { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual product product { get; set; }
    }
}
