//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.LossReportDetails = new HashSet<LossReportDetails>();
            this.outWareDetail = new HashSet<outWareDetail>();
            this.putWareDetail = new HashSet<putWareDetail>();
            this.transferDetail = new HashSet<transferDetail>();
        }
    
        public string productNum { get; set; }
        public string Probarcode { get; set; }
        public string productName { get; set; }
        public long productCount { get; set; }
        public double price { get; set; }
        public string Specifications { get; set; }
        public string productLeixNum { get; set; }
        public string CompanyNum { get; set; }
        public string contents { get; set; }
        public string LocationNum { get; set; }
        public string customerNum { get; set; }
        public int isDel { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual customer customer { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LossReportDetails> LossReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outWareDetail> outWareDetail { get; set; }
        public virtual productLeix productLeix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<putWareDetail> putWareDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transferDetail> transferDetail { get; set; }
    }
}
