//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferDetail
    {
        public string transferNum { get; set; }
        public string productNum { get; set; }
        public long productCount { get; set; }
        public string FrontLocationNum { get; set; }
        public string EndLocationNum { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual product product { get; set; }
    }
}
